<footer role="contentinfo" aria-label="footer"> <!--footer is authored by venson with slight changes made by lira-->
    <div class="footer-content"> 
        <ul class="footer-links">
            <li><a href="https://student-team-ikdwg2wc.atlassian.net/jira/software/projects/POW/boards/34?atlOrigin=eyJpIjoiN2E5OTliZmQ1MWRlNGYyZWIxYWMzYTU4N2FiZTQ4MTEiLCJwIjoiaiJ9" target="_blank">Jira board</a></li>
            <li><a href="https://github.com/Swin-Group-Project/PowerpuffgirlsGroupProject1.git" target="_blank">GitHub repository</a></li>
            <li><a href="mailto:info@powerpuffcorp.com">Email us</a></li>
        </ul>
        <p class="footer-copy">&copy; 2025 Powerpuff Corp. All rights reserved.</p>
    </div>     
    <div class="footer-logo">
        <img src="./images/powerpuffcorpfooterlogoblack.jpg" alt="Powerpuff Corp Logo" width="100px">
    </div>
</footer> <!--footer is authored by venson with slight changes made by lira-->  